global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cookingapp'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']  # or 'localhost:8082' if running locally
